# Flux Tower Data Processing
The following Jupyter Notebook details the upload and filtering of the AmeriFlux flux tower datasets - one of the two datasets necessary for the MAPWAPS project application.

Note: This spearate Jupyter Notebook was created to ensure proper code operation and limited code error (i.e. get the code to work how it needs to) before combining it with the flux tower data as done in the Data Aquisition, Processing and Collation.ipynb Jupyter Notebook.

## Library and Function Imports

This cell imports several essential libraries and sets up functionalities in the Jupyter Notebook, ensuring that they are readily available for implementation and utilization later in the code

In [1]:
import os
import pandas as pd
import re
import os

# Mount google drive in google colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Miscellaneous Functions

### save_df_to_drive
Function that saves a Pandas DataFrame as a csv file to a Google Drive folder specified by a google drive file path

In [2]:
def save_df_to_drive(df, file_path_in_google_drive):
  """
  Function that saves a Pandas DataFrame as a csv file to a Google Drive folder specified by a google drive file path

    parameter:  dataframe -> the Pandas DataFrame needing to be saved
                file_path_in_drive -> Google Drive folder file path that will store the csv file
    return:     void

  """
  try:
      # Ensure the destination directory exists
      destination_dir = os.path.dirname(file_path_in_google_drive)
      os.makedirs(destination_dir, exist_ok=True)

      # Save the DataFrame to the specified file path in Google Drive
      df.to_csv(file_path_in_google_drive, index=False)

      print(f"DataFrame saved to Google Drive at '{file_path_in_google_drive}'")

  except Exception as e:
      print("An error occurred:", str(e))

## Ameriflux Application

Note: the code's commenting often refers to two attempts (where one will always be commented out and the other implemented). Attempt 1 refers to the spatially constricted 66 datasets and attempt 2 refers to the all inclusive 375 datasets. It is important that before running, each of the following cells are implementing the same attempt (i.e. all commented out or included sections agree on which attmept is being implemented).

### Ameriflux Site Overview Data

In [3]:
# Ameriflux allows you to download a CSV file summarising the flux tower sites whose data you have chosen to use and their characteristics.
#     -   the importance of this is so link the flux tower site (Site ID) with its co-ordinate point

# Specify the Google Drive file path of the AmeriFlux Site Overview Dataset
# ------------------------------- ATTEMPT 1 -------------------------------
site_overview_file_path = '/content/drive/My Drive/Colab Notebooks/Data/Flux Tower Data/Ameriflux/AmeriFlux Site Description.csv'
# -------------------------------------------------------------------------

# ------------------------------- ATTEMPT 2 -------------------------------
# site_overview_file_path = '/content/drive/My Drive/Colab Notebooks/Data/Flux Tower Data/Ameriflux/AmeriFlux Site Description Extended.csv'
# -------------------------------------------------------------------------

# Load the AmeriFlux Site Overview Dataset into a Pandas DataFrame
df_site_overview = pd.read_csv(site_overview_file_path, delimiter=';')

# df_site_overview.head()                               # Uncomment to ensure proper csv file upload

# Filter the AmeriFlux Site Overview Dataset
df_site_overview['Years of AmeriFlux BASE Data'] = df_site_overview['Years of AmeriFlux BASE Data'].astype(str)                               # Converts list to string
df_site_overview['Start Year'] = df_site_overview['Years of AmeriFlux BASE Data'].apply(lambda x: min(map(int, x.strip('()').split(','))))    # Extracts the first year from the list
df_site_overview['End Year'] = df_site_overview['Years of AmeriFlux BASE Data'].apply(lambda x: max(map(int, x.strip('()').split(','))))      # Extracts the last year from the list

# df_site_overview.head()                               # Uncomment to ensure proper start and end year extraction

important_columns = ['Site ID', 'Latitude (degrees)', 'Longitude (degrees)', 'Start Year', 'End Year']    # Specifies important columns (the rest will be discarded for simplicity)
df_site_overview_filtered = df_site_overview[important_columns]                                           # Creates a new filtered Pandad DataFrame with only the important columns

# Saves the filtered AmeriFlux Site Overview Dataset the a specified Google Drive file path
# ------------------------------- ATTEMPT 1 -------------------------------
save_df_to_drive(df_site_overview_filtered, '/content/drive/My Drive/Colab Notebooks/Data/Flux Tower Data/Ameriflux/AmeriFlux Site Description Filtered.csv')
# -------------------------------------------------------------------------

# ------------------------------- ATTEMPT 2 -------------------------------
# save_df_to_drive(df_site_overview_filtered, '/content/drive/My Drive/Colab Notebooks/Data/Flux Tower Data/Ameriflux/AmeriFlux Site Description Extended Filtered.csv')
# -------------------------------------------------------------------------

# df_site_overview_filtered.head()                      # Uncomment to view simplified/ filtered database containing the needed variables
# print(df_site_overview_filtered.info())               # Uncomment to view the Pandas DataFrame's characteristics (# columns, # rows, variables, variable types)

DataFrame saved to Google Drive at '/content/drive/My Drive/Colab Notebooks/Data/Flux Tower Data/Ameriflux/AmeriFlux Site Description Filtered.csv'

### Ameriflux Individual Datasets

In [4]:
# Specify the Google Drive file path of the individual AmeriFlux Flux Tower Datasets
folder_path = '/content/drive/My Drive/Colab Notebooks/Data/Flux Tower Data/Ameriflux/Original'
os.chdir(folder_path)                             # Change the operating directory to the folder path

# Load a list of the current directory's contents
contents = os.listdir()

# Print the contents
print("Contents of the directory:")
i = 0
for item in contents:
    print(item)
    i = i +1

print("Number of Datasets: " + str(i))            # Ensure the correct number of datasets have been uploaded

Contents of the directory:
AMF_US-Snd_BASE_HH_2-1.csv
AMF_US-SP2_BASE_HH_3-1.csv
AMF_US-SP3_BASE_HH_3-1.csv
AMF_US-SP1_BASE_HH_4-1.csv
AMF_US-Dia_BASE_HH_1-1.csv
AMF_US-Elm_BASE_HH_4-1.csv
AMF_US-Esm_BASE_HH_5-1.csv
AMF_US-Srr_BASE_HH_1-5.csv
AMF_US-Tw3_BASE_HH_5-5.csv
AMF_US-SuS_BASE_HH_2-5.csv
AMF_US-KS2_BASE_HH_3-5.csv
AMF_US-Tw2_BASE_HH_2-5.csv
AMF_US-SuM_BASE_HH_2-5.csv
AMF_US-KS1_BASE_HH_3-5.csv
AMF_US-SuW_BASE_HH_2-5.csv
AMF_US-Fwf_BASE_HH_8-5.csv
AMF_US-Fuf_BASE_HH_6-5.csv
AMF_US-Fmf_BASE_HH_6-5.csv
AMF_US-SRC_BASE_HH_6-5.csv
AMF_US-Lin_BASE_HH_2-5.csv
AMF_US-Blo_BASE_HH_4-5.csv
AMF_US-KS3_BASE_HH_1-5.csv
AMF_US-SP4_BASE_HH_3-5.csv
AMF_US-DPW_BASE_HH_1-5.csv
AMF_US-EDN_BASE_HH_2-5.csv
AMF_US-ASM_BASE_HH_1-5.csv
AMF_US-ASL_BASE_HH_1-5.csv
AMF_US-Tw5_BASE_HH_3-5.csv
AMF_US-PSL_BASE_HH_1-5.csv
AMF_US-PSH_BASE_HH_1-5.csv
AMF_US-ASH_BASE_HH_1-5.csv
AMF_US-Snf_BASE_HH_3-5.csv
AMF_US-LS1_BASE_HH_1-5.csv
AMF_US-LS2_BASE_HH_1-5.csv
AMF_US-Tw1_BASE_HH_9-5.csv
AMF_US-Sne_BASE_HH_7-5.csv
AMF_US-Tw4_BASE_HH_12-5.csv
AMF_US-CMW_BASE_HH_2-5.csv
AMF_US-SRS_BASE_HH_3-5.csv
AMF_US-Myb_BASE_HH_13-5.csv
AMF_US-ONA_BASE_HH_3-5.csv
AMF_US-PAS_BASE_HH_1-5.csv
AMF_US-MtB_BASE_HH_4-5.csv
AMF_US-DS3_BASE_HH_1-5.csv
AMF_US-Var_BASE_HH_18-5.csv
AMF_US-Dmg_BASE_HH_1-5.csv
AMF_US-RGB_BASE_HH_3-5.csv
AMF_US-RGo_BASE_HH_2-5.csv
AMF_US-xDS_BASE_HH_6-5.csv
AMF_US-xSR_BASE_HH_7-5.csv
AMF_US-xPU_BASE_HH_5-5.csv
AMF_US-SRG_BASE_HH_15-5.csv
AMF_US-xSJ_BASE_HH_6-5.csv
AMF_US-xSB_BASE_HH_6-5.csv
AMF_US-xCL_BASE_HH_6-5.csv
AMF_US-Hsm_BASE_HH_2-5.csv
AMF_US-Bi1_BASE_HH_9-5.csv
AMF_US-xSP_BASE_HH_7-5.csv
AMF_US-CGG_BASE_HH_1-5.csv
AMF_US-Whs_BASE_HH_21-5.csv
AMF_US-Ton_BASE_HH_17-5.csv
AMF_US-Twt_BASE_HH_7-5.csv
AMF_US-Wkg_BASE_HH_21-5.csv
AMF_US-SRM_BASE_HH_26-5.csv
AMF_US-Bi2_BASE_HH_14-5.csv
AMF_US-xTE_BASE_HH_7-5.csv
Number of Datasets: 66

In [6]:
# The remainder of the application will be performed on a single dataset (first in list) and later extrapolated

file_name = 'AMF_US-ASH_BASE_HH_1-5.csv'                        # File name specification (first in directory list)
csv_path = folder_path+"/"+file_name                            # Google Drive file path of the individual AmeriFlux Flux Tower with name specified by file_name
df = pd.read_csv(csv_path, delimiter=',', skiprows=2)           # Load the individual AmeriFlux Flux Tower Dataset into a Pandas DataFrame
      # Note: the correct seperation delimeter is , and the first 2 rows are skipped as they specify the site name and dataset version

# df.head()                      # Uncomment to view the individual AmeriFlux Flux Tower Dataset
# print(df.info())               # Uncomment to view the Pandas DataFrame's characteristics (# columns, # rows, variables, variable types)

,TIMESTAMP_START,TIMESTAMP_END,CO2,FC_SSITC_TEST,FC,H2O,LE_SSITC_TEST,LE,H_SSITC_TEST,H,...,USTAR,FETCH_MAX,FETCH_70,FETCH_80,FETCH_90,FETCH_FILTER,WS,WD,NETRAD,G
0,201601010000,201601010030,-9999.0,-9999,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0
1,201601010030,201601010100,-9999.0,-9999,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0
2,201601010100,201601010130,-9999.0,-9999,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0
3,201601010130,201601010200,-9999.0,-9999,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0
4,201601010200,201601010230,-9999.0,-9999,-9999.0,-9999.0,-9999,-9999.0,-9999,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0

#### timestamp_separate
Function that uses string handlng techniques to seperate the TIME_STAMP (YYYYMMDDHHMM) into TIME_STAMP_DATE (YYYYMMDD) and TIME_STAMP_TIME (HHMM) in order to isolate the date variable for later use.

In [16]:
def timestamp_separate(df):

  """
  Function that uses string handling techniques to separate the flux tower variable TIME_STAMP (YYYYMMDDHHMM)
  into TIME_STAMP_DATE (YYYYMMDD) and TIME_STAMP_TIME (HHMM) in order to isolate the date variable for later use

    parameter:  df -> the Pandas DataFrame storing the original, unfiltered flux tower data
    return:     df_time_seperated -> the Pandas DataFrame with manipulated date and time variables

  """

  # Manipulates the TIMESTAMP (both START and END) columns to split into DATE and TIME separately
  # Convert TIMESTAMP columns to string
  df['TIMESTAMP_START'] = df['TIMESTAMP_START'].astype(str)
  df['TIMESTAMP_END'] = df['TIMESTAMP_END'].astype(str)

  # Extract TIMESTAMP_DATE (YYMMDD) and TIMESTAMP_TIME (HHMM) (for both START and END) with string handling principles
  df['TIMESTAMP_START_DATE'] = df['TIMESTAMP_START'].str[:8]
  df['TIMESTAMP_START_TIME'] = df['TIMESTAMP_START'].str[8:]
  df['TIMESTAMP_END_DATE'] = df['TIMESTAMP_END'].str[:8]
  df['TIMESTAMP_END_TIME'] = df['TIMESTAMP_END'].str[8:]

  # @ this stage the count variable should be 48 because the sampling rate is 30 minutes (24hrs x 2) and no entries have been removed
  df['COUNT'] = df.groupby('TIMESTAMP_START_DATE')['TIMESTAMP_START_DATE'].transform('count')

  # Specify TIMESTAMP columns order
  start_columns = [
      'TIMESTAMP_START', 'TIMESTAMP_START_DATE', 'TIMESTAMP_START_TIME',
      'TIMESTAMP_END', 'TIMESTAMP_END_DATE', 'TIMESTAMP_END_TIME'
  ]

  # Define the df order with TIMESTAMP columns first and remaining columns in their original order
  desired_order = start_columns + [col for col in df.columns if col not in start_columns]
  df_time_seperated = df[desired_order]

  return df_time_seperated

# -----------------------------------------------------------------------------------------------------------------
# Example usage
df_time_seperated = timestamp_separate(df)

# df_time_seperated.head()                      # Uncomment to view the individual AmeriFlux Flux Tower Dataset with separated timestamps
# print(df_time_seperated.info())               # Uncomment to view the Pandas DataFrame's characteristics (# columns, # rows, variables, variable types)

,TIMESTAMP_START,TIMESTAMP_START_DATE,TIMESTAMP_START_TIME,TIMESTAMP_END,TIMESTAMP_END_DATE,TIMESTAMP_END_TIME,CO2,FC_SSITC_TEST,FC,H2O,...,FETCH_MAX,FETCH_70,FETCH_80,FETCH_90,FETCH_FILTER,WS,WD,NETRAD,G,COUNT
0,201601010000,20160101,0000,201601010030,20160101,0030,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
1,201601010030,20160101,0030,201601010100,20160101,0100,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
2,201601010100,20160101,0100,201601010130,20160101,0130,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
3,201601010130,20160101,0130,201601010200,20160101,0200,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
4,201601010200,20160101,0200,201601010230,20160101,0230,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48

#### check_LE
Function that check if a dataset has an LE column and if not finds a LE column derivation and renames it LE for simplified future use
- Note: LE column derivation refers to a column that stores LE values but under a different column name (e.g. LE_1.1.1)

In [19]:
def check_LE(df):
    """
    Function that check if a dataset has an LE column and if not finds a LE column derivation and renames it LE for simplified future use
      Note: LE column derivation refers to a column that stores LE values but under a different column name (e.g. LE_1.1.1)

    parameter:  df -> the Pandas DataFrame storing the original flux tower data (with LE or LE derived columns)
    return:     df_with_LE -> the Pandas DataFrame with LE column name

    """
    column_name = 'LE'                        # Column of interest is the Latent Heat Flux (LE)
    df_with_LE = df

    if not column_name in df.columns:         # The Pandas DataFrame does not have a column with name 'LE'
      try:
          # Find the first column that starts with 'LE'
          LE_column = next(col for col in df.columns if col.startswith('LE'))

          # Rename the column to 'LE'
          df_with_LE = df.rename(columns={LE_column: 'LE'}, inplace=True)
      except StopIteration:
          # The Pandas DataFrame does not have a column name that starts with 'LE'
          print("No column starts with 'LE'")

    return df_with_LE

# -----------------------------------------------------------------------------------------------------------------
# Example usage
df_with_LE = check_LE(df_time_seperated)

# ddf_with_LEf.head()                       # Uncomment to view the individual AmeriFlux Flux Tower Dataset with ensured LE column name
# print(df_with_LE.info())                  # Uncomment to view the Pandas DataFrame's characteristics (# columns, # rows, variables, variable types)

,TIMESTAMP_START,TIMESTAMP_START_DATE,TIMESTAMP_START_TIME,TIMESTAMP_END,TIMESTAMP_END_DATE,TIMESTAMP_END_TIME,CO2,FC_SSITC_TEST,FC,H2O,...,FETCH_MAX,FETCH_70,FETCH_80,FETCH_90,FETCH_FILTER,WS,WD,NETRAD,G,COUNT
0,201601010000,20160101,0000,201601010030,20160101,0030,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
1,201601010030,20160101,0030,201601010100,20160101,0100,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
2,201601010100,20160101,0100,201601010130,20160101,0130,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
3,201601010130,20160101,0130,201601010200,20160101,0200,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48
4,201601010200,20160101,0200,201601010230,20160101,0230,-9999.0,-9999,-9999.0,-9999.0,...,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,-9999.0,-9999.0,48

#### remove_null
Function that removes any data entry/ row that has a null (-9999) Latent Heat Flux (LE) variable
- there is commented out section of code that will remove any entry with a null value (LE variable or otherwise)

In [ ]:
def remove_null(df):

  """
  Function that removes any data entry/ row that has a null (-9999) Latent Heat Flux (LE) variable

    parameter:  df -> the Pandas DataFrame with LE null (-9999) values
    return:     df_without_LE_null_values -> the Pandas DataFrame with removed LE null (-9999) values

  """

  # # ----------------------- use if all entries with null values need removal -----------------------
  # # Removes any row with a null (-9999) value
  # columns_to_check = df.columns[2:]
  # void_filter_boolean = df[columns_to_check].apply(lambda x: (x != -9999).all(), axis=1) # creates a boolean mask to identify the presence of -9999 values
  # df_without_null_values = df[void_filter_boolean] # applies mask to df
  # # ------------------------------------------------------------------------------------------------

  # Removes any row with a LE column null (-9999) value
  df = df[df['LE'] != -9999]
  del df['COUNT']
  df['COUNT'] = df.groupby('TIMESTAMP_START_DATE')['TIMESTAMP_START_DATE'].transform('count')     # Counts the number of entries per date
  df_without_LE_null_values = df

  return df_without_LE_null_values

# -----------------------------------------------------------------------------------------------------------------
# Example usage
df_without_LE_null_values = remove_null(df_with_LE)

# df_without_LE_null_values.head()                      # Uncomment to view the individual AmeriFlux Flux Tower Dataset without null LE values
# print(df_without_LE_null_values.info())               # Uncomment to view the Pandas DataFrame's characteristics (# columns, # rows, variables, variable types)

<ipython-input-12-d4499ea0b87f>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['COUNT'] = df.groupby('TIMESTAMP_START_DATE')['TIMESTAMP_START_DATE'].transform('count')

,TIMESTAMP_START,TIMESTAMP_START_DATE,TIMESTAMP_START_TIME,TIMESTAMP_END,TIMESTAMP_END_DATE,TIMESTAMP_END_TIME,CO2,FC_SSITC_TEST,FC,H2O,...,FETCH_MAX,FETCH_70,FETCH_80,FETCH_90,FETCH_FILTER,WS,WD,NETRAD,G,COUNT
13668,201610111800,20161011,1800,201610111830,20161011,1830,398.732153,0,0.550698,13.490808,...,23.283675,42.569984,50.945399,63.777594,1,1.816487,14.33499,-59.614141,-9999.0,12
13669,201610111830,20161011,1830,201610111900,20161011,1900,401.564254,0,2.161463,13.240753,...,13.017980,111.000000,198.000000,512.000000,1,1.171787,10.45120,-83.389953,-9999.0,12
13670,201610111900,20161011,1900,201610111930,20161011,1930,407.379907,0,2.158860,13.003748,...,15.486547,135.000000,245.000000,642.000000,1,1.133326,5.03818,-79.955308,-9999.0,12
13671,201610111930,20161011,1930,201610112000,20161011,2000,405.967576,0,2.712031,12.580039,...,16.824972,149.000000,269.000000,709.000000,1,0.934688,6.78320,-76.725903,-9999.0,12
13672,201610112000,20161011,2000,201610112030,20161011,2030,411.372277,0,1.583108,12.588766,...,20.331212,181.000000,329.000000,873.000000,1,0.729078,16.55023,-71.707123,-9999.0,12

#### group_df
Function that will group a dataframe by the date and add up each of its other columns - this is because we want to deal with daily ET estimates.
- It will also filter the dataframe to obtain only the neccessary variables: Date, LE, COUNT
- If the COUNT variable is not 2304 (48 x 48) then that row is removed because it signals an 'incomplete' dataset in that due to null value removals, there is not a full days worth of collected data.

In [ ]:
def group_df(df):

  """
  Function that groups a Pandas DataFrame by the date variable and adds up the other columns

    parameter:  df -> the Pandas DataFrame with half hourly data readings (i.e. 48 readings per day - unless null values have been removed)
    return:     df_grouped -> the Pandas DataFrame with grouped entries/ rows and daily LE values
                              (only entries with a full day of recordings will be included - i.e. the daily count of 2304 = 48 x 48)

  """

  df_simplified = df[['TIMESTAMP_START_DATE','LE','COUNT']]         # Creates a new filtered Pandad DataFrame with only the important columns
  # df_simplified.head()           # Uncomment to ensure proper dataframe simplification

  # Group by 'TIMESTAMP_START_DATE' and sum the 'LE' and 'COUNT' columns
  df_grouped = df_simplified.groupby('TIMESTAMP_START_DATE').agg({'LE': 'sum', 'COUNT': 'sum'}).reset_index()
  df_grouped.rename(columns={'TIMESTAMP_START_DATE': 'DATE', 'LE': 'DAILY LE', 'COUNT': 'DAILY COUNT'}, inplace=True) # Rename the columns

  # Drop all 'incomplete' entries (those that do not have a days worth of data)
  df_grouped = df_grouped[df_grouped['DAILY COUNT'] == 2304]

  return df_grouped

# -----------------------------------------------------------------------------------------------------------------
# Example usage
df_grouped = group_df(df_without_LE_null_values)

# df.head()                      # Uncomment to view the individual AmeriFlux Flux Tower Dataset that have been grouped by date
# print(df.info())               # Uncomment to view the Pandas DataFrame's characteristics (# columns, # rows, variables, variable types)

       DATE     DAILY LE  DAILY COUNT
1  20161012  2717.725462         2304
2  20161013  2288.402731         2304
3  20161014  3377.478525         2304
4  20161015  3096.250774         2304
5  20161016  2987.214642         2304